language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  
before_script:
  - composer require --dev satooshi/php-coveralls:dev-master
  - composer install
  
after_script:
  - php bin/coveralls -v

script: 
  - phpunit --coverage-text

matrix:
     allow_failures:
         - php: hhvm  
